apps:

  - script: index.js
    name: digit-marketing
    instances: 0
    exec_mode: cluster
    watch: false
    autorestart: true
    ignore_watch:
        - logs
        - node_modules
        - worker\.js
        - \.git/index\.lock
        - \.log
        - \.lock
    watch_options:
        followSymlinks: false